require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  Exclude:
    - Steepfile

Metrics/MethodLength:
  Exclude:
    - 'test/**/*.rb'

Layout/LineLength:
  Max: 140
  Exclude:
    - 'test/**/*.rb'

Metrics/ParameterLists:
  Max: 6
